### Import Libraries

In [591]:
import numpy as np
np.set_printoptions(suppress=True, precision=4)

### Initial Weight Vectors

In [592]:
W1 = np.array([[0.5, 1.5, 0.8], [0.8, 0.2, -1.6]])
W2 = np.array([[0.9, -1.7, 1.6], [1.2, 2.1, -0.2]])

In [593]:
X1 = np.array([1.0, 0.7, 1.2])    # feature vector input for first layer
X2 = np.array([1.0, 0.0, 0.0])    # input for second layer
t = np.array([1.0, 0.0])            # target output

### Activation Function

In [594]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [595]:
def sigmoid_2_output(y: np.array):
    return np.array([1 if i > 0.5 else 0 for i in y])

### Feed Forward Function

In [596]:
def feed_forward(feature_vector, weight_vector):
    return sigmoid(np.dot(weight_vector, feature_vector))

### Back Propagation Function

In [597]:
def back_propagation(W, X, delta_vector, learning_rate):
    n, m = W.shape
    for j in range(n):
        for i in range(m):
            W[j, i] = W[j, i] - learning_rate * delta_vector[j] * X[i]
    return W

### Delta Vector (Hidden Layer)

In [598]:
def delta_hidden_layer(next_delta_vector, W, output_vector):
    n, m = W.shape
    delta_vector = np.zeros(m - 1)

    for i in range(m - 1):
        for j in range(n):
            delta_vector[j] += next_delta_vector[i] * W[i , j + 1]

    delta_vector = output_vector * (1 - output_vector) * delta_vector
    return delta_vector

### Multi Layer Perceptron

In [599]:
def multilayer_perceptron(X1, X2, W1, W2, t, learning_rate = 0.001, max_epochs = 1000):
     for epoch in range(max_epochs):
          print(f"Epoch {epoch + 1}")
          o1 = feed_forward(X1, W1)
          X2[1], X2[2] = o1[0], o1[1]
          o2 = feed_forward(X2, W2)
          output = sigmoid_2_output(o2)
          if(np.array_equal(output, t)):
               print(f"Converged after {epoch + 1} epochs")
               break
          else:
               delta_2_vector = (o2 - t) * o2 * (1 - o2)
               # print(f"Delta 2: {delta_2_vector}")
               W2 = back_propagation(W2, X2, delta_2_vector, learning_rate)
               # print("O1 : ", o1)
               delta_1_vector = delta_hidden_layer(delta_2_vector, W2, o1)
               # print(f"Delta 1: {delta_1_vector}")
               W1 = back_propagation(W1, X1, delta_1_vector, learning_rate)
          print(W1, '\n\n' , W2)
     else:
          print("Did not converge after max epochs")
     return W1, W2

In [600]:
W1, W2 = multilayer_perceptron(X1, X2, W1, W2, t, 0.5, 1000)

Epoch 1
[[ 0.4893  1.4925  0.7871]
 [ 0.8229  0.2161 -1.5725]] 

 [[ 0.9689 -1.6363  1.6188]
 [ 1.1801  2.0815 -0.2054]]
Epoch 2
[[ 0.4789  1.4853  0.7747]
 [ 0.8455  0.2319 -1.5454]] 

 [[ 1.0337 -1.5765  1.6374]
 [ 1.1593  2.0624 -0.2114]]
Epoch 3
[[ 0.469   1.4783  0.7628]
 [ 0.8674  0.2472 -1.5191]] 

 [[ 1.0938 -1.5212  1.6554]
 [ 1.1377  2.0425 -0.2179]]
Epoch 4
[[ 0.4595  1.4716  0.7514]
 [ 0.8884  0.2618 -1.494 ]] 

 [[ 1.1489 -1.4706  1.6727]
 [ 1.1151  2.0218 -0.225 ]]
Epoch 5
[[ 0.4504  1.4653  0.7405]
 [ 0.9082  0.2757 -1.4701]] 

 [[ 1.1991 -1.4246  1.6891]
 [ 1.0916  2.0002 -0.2327]]
Epoch 6
[[ 0.4416  1.4591  0.73  ]
 [ 0.9269  0.2889 -1.4477]] 

 [[ 1.2445 -1.3831  1.7046]
 [ 1.0669  1.9777 -0.241 ]]
Epoch 7
[[ 0.4331  1.4532  0.7198]
 [ 0.9446  0.3012 -1.4265]] 

 [[ 1.2857 -1.3455  1.7191]
 [ 1.0412  1.9542 -0.2501]]
Epoch 8
[[ 0.4249  1.4474  0.7099]
 [ 0.9611  0.3128 -1.4066]] 

 [[ 1.3229 -1.3116  1.7326]
 [ 1.0142  1.9296 -0.26  ]]
Epoch 9
[[ 0.4168  1.4417  0.700

In [601]:
print("Final weight vector:")
print("W1:", W1)
print("W2:", W2)

Final weight vector:
W1: [[ 0.2068  1.2948  0.4482]
 [ 1.2904  0.5433 -1.0115]]
W2: [[ 1.6883 -0.987   1.8977]
 [-0.2046  0.8648 -0.8714]]
